[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
ffi = true
fs_permissions = [{ access = true, path = "./.forge-snapshots/"}]


# See more config options https://github.com/gakonst/foundry/tree/master/config
